/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.world

fun olaMundo(nome: String) {
    println("Olá $nome!")
}

fun main(args: Array<String>) {
    olaMundo(args[0])
}
